---
  - hosts: centos
    remote_user: vagrant
    become: true
    gather_facts: no
    vars:
      version_number: '2.5.0'
      server: centos
    tasks:
      - name: Jinja2 file copy
        template:
          src: apache.j2
          dest: /tmp/apache_version.txt
